
on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      environment: production
      
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0

      - name: Terraform Init
        id: init
        run: | 
          cd ./2022-08-20-tf-create-aa-with-source-control
          terraform init

      - name: Terraform Validate
        id: validate
        run: |
          terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
          cd ./2022-08-20-tf-create-aa-with-source-control
          terraform plan \
            -var="subscription_id=$ARM_SUBSCRIPTION_ID" \
            -var="tenant_id=$ARM_TENANT_ID" \
            -var="client_id=$ARM_CLIENT_ID" \
            -var="client_secret=$ARM_CLIENT_SECRET" \
            -out "tf.plan"
        continue-on-error: false

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd ./2022-08-20-tf-create-aa-with-source-control
          terraform apply -auto-approve -input=false -destroy ./tf.plan
        continue-on-error: false