
on:
  workflow_dispatch:

jobs:
  Connectivity:
    runs-on: ubuntu-latest
        
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      
    steps:
      - uses: actions/checkout@v3

      - name: 'Terraform init'
        id: init
        run: |
          cd ./2022-08-03-github-actions-setup
          terraform init
      
      - name: 'Terraform plan'
        id: plan
        run: |
          terraform plan